Kirill_Zharov_HW_13_done
eugene-okulik/Kirill_Auto pull request #12
Opened 2024-06-18 11:28 UTC by Kirill-Zharoff

2024-06-18 14:46 UTC, eugene-okulik requested changes
Всё хорошо, кроме того, что это задание направлено на практику построения пути к файлу.

2024-06-18 14:46 UTC, eugene-okulik commented on homework/kirill_zharov/HW _13/task.py
> +url = 'https://raw.githubusercontent.com/eugene-okulik/Kirill_Auto/main/homework/eugene_okulik/hw_13/data.txt'
Файл нужно читать из файлов компа, а не из интернета. Ведь файл и так уже находится на твоем компе (если, конечно, ты не забываешь обновлять ветку main)

2024-06-19 06:25 UTC, Kirill-Zharoff commented on homework/kirill_zharov/HW _13/task.py
> +url = 'https://raw.githubusercontent.com/eugene-okulik/Kirill_Auto/main/homework/eugene_okulik/hw_13/data.txt'
обновляю конечно), подправлю

2024-06-19 10:33 UTC, Kirill-Zharoff commented
не получается получить base_path = os.path.dirname(__file__), не тот путь указывает(

2024-06-19 15:40 UTC, eugene-okulik commented
> не получается получить `base_path = os.path.dirname(__file__)`, не тот путь указывает(

Не бывает такого. Возможно, ты какой-то другой путь ждешь? Оно возвращает путь к тому файлу, в котором у тебя код написан, не к файлу с данными для домашки. И уже от того места, где лежит твой файл, ты можешь построить путь к файлу, как я показывал в видео где строил путь к файлу file.txt Алины.

2024-06-20 10:19 UTC, eugene-okulik requested changes
У тебя работает?  
У меня нет:
```
/home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/homework/eugene_okulik/hw_13/data.txt
Traceback (most recent call last):
  File "/home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/task.py", line 11, in <module>
    with open(config_path) as config_path:
FileNotFoundError: [Errno 2] No such file or directory: '/home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/homework/eugene_okulik/hw_13/data.txt'
```
Ты строишь base_path к папке, где находится файл с кодом, который ты пишешь, а потом от нее строишь путь к файлу с данными, но в папке, где ты выполняешь домашнее задание нет папки homework

2024-06-20 12:17 UTC, Kirill-Zharoff commented
> У тебя работает? У меня нет:
> 
> ```
> /home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/homework/eugene_okulik/hw_13/data.txt
> Traceback (most recent call last):
>   File "/home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/task.py", line 11, in <module>
>     with open(config_path) as config_path:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/homework/eugene_okulik/hw_13/data.txt'
> ```

> Ты строишь base_path к папке, где находится файл с кодом, который ты пишешь, а потом от нее строишь путь к файлу с данными, но в папке, где ты выполняешь домашнее задание нет папки homework

ммм.. не знаю в чем проблема, с файлом Алины как в видео, у меня тоже не получается(, задание вроде простое, может у меня с директориями чего не так.

2024-06-21 14:48 UTC, eugene-okulik commented
> > У тебя работает? У меня нет:
> > ```
> > /home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/homework/eugene_okulik/hw_13/data.txt
> > Traceback (most recent call last):
> >   File "/home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/task.py", line 11, in <module>
> >     with open(config_path) as config_path:
> > FileNotFoundError: [Errno 2] No such file or directory: '/home/eugene/projects/Kirill_Auto/homework/kirill_zharov/HW_13/homework/eugene_okulik/hw_13/data.txt'
> > ```
> 
> > Ты строишь base_path к папке, где находится файл с кодом, который ты пишешь, а потом от нее строишь путь к файлу с данными, но в папке, где ты выполняешь домашнее задание нет папки homework
> 
> ммм.. не знаю в чем проблема, с файлом Алины как в видео, у меня тоже не получается(, задание вроде простое, может у меня с директориями чего не так.

Просто в твоем репозитории нет файла Алины )))

2024-06-21 14:51 UTC, eugene-okulik approved these changes
Теперь отлично, только не называй папки с пробелами внутри. Однажды проблем не оберешься.

2024-06-21 14:51 UTC, merged

2024-06-21 15:33 UTC, Kirill-Zharoff commented
> Теперь отлично, только не называй папки с пробелами внутри. Однажды проблем не оберешься.
Ура!!!